version: '3'

services:
  core:
    build:
      context: core/
    #depends_on:
    #  - "db"
    volumes:
      - /var/log/meteor/core:/var/log/meteor/core
    networks:
      meteornet:
        ipv4_address: 172.69.1.1

  db:
    build:
      context: database/
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      meteornet:
        ipv4_address: 172.69.1.2
  
  daddytops:
    build:
      context: listeners/daddy_tops/
    ports:
      - "8888:8888"
    volumes:
      - /var/log/meteor/daddytops:/var/log/meteor/daddytops
    restart: always
    networks:
      meteornet: 
        ipv4_address: 172.69.1.3


networks:
  meteornet:
    ipam:
      driver: default
      config:
        - subnet: 172.69.0.0/16