version: '3'

services:
  core:
    build:
      context: core/
    depends_on:
      - "db"
    volumes:
      - /var/log/meteor/core:/var/log/meteor/core
    command: sh -c "/wait && /go/bin/core"
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=3
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - LOGPATH=/var/log/meteor/core/core.log
    networks:
      meteornet:
        ipv4_address: 172.16.77.2

  db:
    build:
      context: database/
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      meteornet:
        ipv4_address: 172.16.77.3
  
  daddytops:
    build:
      context: listeners/daddy_tops/
    ports:
      - "8888:8888"
    volumes:
      - /var/log/meteor/daddytops:/var/log/meteor/daddytops
    environment:
      - CORE_SERVER=172.16.77.2
    restart: always
    networks:
      meteornet: 
        ipv4_address: 172.16.77.4

  nest:
    build:
      context: listeners/nest/
    ports:
      - "45678:45678"
    volumes:
      - /var/log/meteor/nest:/var/log/meteor/nest
    restart: always
    networks:
      meteornet: 
        ipv4_address: 172.16.77.5

  petrie:
    build:
      context: listeners/petrie/
    ports:
      - "10666:10666"
    volumes:
      - /var/log/meteor/petrie:/var/log/meteor/petrie
    environment:
      - PETRIE_PORT=10666
      - CORE_SERVER=172.16.77.2
      - LOGPATH=/var/log/meteor/petrie/petrie.log
    restart: always
    networks:
      meteornet: 
        ipv4_address: 172.16.77.6


networks:
  meteornet:
    ipam:
      driver: default
      config:
        - subnet: 172.16.77.0/24