version: '3'

services:
  core:
    build:
      context: core/
    depends_on:
      - "db"
    volumes:
      - /var/log/meteor/core:/var/log/meteor/core
    networks:
      meteornet:
        ipv4_address: 172.69.1.1

  db:
    build:
      context: database/
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      meteornet:
        ipv4_address: 172.69.1.2
  
  daddytops:
    build:
      context: modules/daddy_tops/
    ports:
      - "8888:8888"
    volumes:
      - /var/log/meteor/daddytops:/var/log/meteor/daddytops
      - ./dtdb-data:/etc/dbfiles
    restart: always
    networks:
      meteornet: 
        ipv4_address: 172.69.1.3

  petrie:
    build:
      context: modules/petrie/
    ports:
      - "5657:5657"
    volumes:
      - /var/log/meteor/petrie:/var/log/meteor/petrie
    restart: always
    networks:
      meteornet:
        ipv4_address: 172.69.1.4

  littlefoot:
    build:
      context: modules/little_foot/
    ports:
      - "80:80"
    volumes:
      - /var/log/meteor/littlefoot:/var/log/meteor/littlefoot
    restart: always
    networks:
      meteornet:
        ipv4_address: 172.69.1.5

networks:
  meteornet:
    ipam:
      driver: default
      config:
        - subnet: 172.69.0.0/16